name: Build Readthedocs of Docs

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Hosted GitHub runners have 7 GB of memory available, let's use 6 GB
  NODE_OPTIONS: --max-old-space-size=6144

jobs:

  rtd-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.10
        cache: "pip"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Setup R
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.2
    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: sphinx-inline-tabs, sphinx-copybutton, sphinx-thebe, sphinx-book
    - name: Setup Jupyter Notebook Kernel
      run: |
        Rscript -e 'IRkernel::installspec()' # Add R kernel to Jupyter

    # Build sphinx
    - name: Build RTD of docs
      run: |
        jupyter-book config sphinx docs/

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/
        publish_branch: rtd-build
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"